# Generated by Django 4.0.3 on 2022-05-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoriy',
            new_name='category',
        ),
    ]
